apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: node-sample-ingress
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`hallo.local`)
    kind: Rule
    services:
    - name: node-sample-service
      port: 80
